# -*- coding: utf-8 -*-
from skidl import *

@subcircuit
def top():
    # Local nets
    _p_3_3V = Net('+3.3V')
    _p_7_5V = Net('+7.5V')
    BLUE = Net('/BLUE')
    BOOST = Net('/BOOST')
    Buzzer = Net('/Buzzer')
    CC1 = Net('/CC1')
    CC1_ = Net('/CC1_')
    CC2 = Net('/CC2')
    CC2_ = Net('/CC2_')
    CURRENT = Net('/CURRENT')
    ENC_A = Net('/ENC_A')
    ENC_B = Net('/ENC_B')
    GREEN = Net('/GREEN')
    H_sense1 = Net('/H_sense1')
    H_sense2 = Net('/H_sense2')
    Handle_inp1 = Net('/Handle_inp1')
    Handle_inp2 = Net('/Handle_inp2')
    Heater = Net('/Heater')
    I_LEAK = Net('/I_LEAK')
    NRST = Net('/NRST')
    RED = Net('/RED')
    S1 = Net('/S1')
    SCL = Net('/SCL')
    SDA = Net('/SDA')
    SD_CS = Net('/SD_CS')
    SPI_CS = Net('/SPI_CS')
    SPI_DC = Net('/SPI_DC')
    SPI_MOSI = Net('/SPI_MOSI')
    SPI_RST = Net('/SPI_RST')
    SPI_SCK = Net('/SPI_SCK')
    SW1 = Net('/SW1')
    SW2 = Net('/SW2')
    SW3 = Net('/SW3')
    SWCLK = Net('/SWCLK')
    SWDIO = Net('/SWDIO')
    S_sense = Net('/S_sense')
    Stand_inp = Net('/Stand_inp')
    TC = Net('/TC')
    USART_RX = Net('/USART_RX')
    USART_TX = Net('/USART_TX')
    USB_D_p = Net('/USB_D+')
    USB_D_n = Net('/USB_D-')
    USR1 = Net('/USR1')
    USR2 = Net('/USR2')
    USR3 = Net('/USR3')
    USR4 = Net('/USR4')
    VBUS = Net('/VBUS')
    VBUS_IN = Net('/VBUS_IN')
    VCCA = Net('/VCCA')
    VDD_IN = Net('/VDD_IN')
    VDD_IN_USBCPD = Net('/VDD_IN_USBCPD')
    Earth = Net('Earth')
    GND = Net('GND')
    Net__C24_Pad1_ = Net('Net-(C24-Pad1)')
    Net__C9_Pad1_ = Net('Net-(C9-Pad1)')
    Net__IC2_Pad1_ = Net('Net-(IC2-Pad1)')
    Net__IC2_Pad7_ = Net('Net-(IC2-Pad7)')
    Net__IC2A_pos = Net('Net-(IC2A-+)')
    Net__IC2A_neg = Net('Net-(IC2A--)')
    Net__IC2B_pos = Net('Net-(IC2B-+)')
    Net__IC2B_neg = Net('Net-(IC2B--)')
    Net__IC3_CB_ = Net('Net-(IC3-CB)')
    Net__IC3_FB_ = Net('Net-(IC3-FB)')
    Net__IC3_SW_ = Net('Net-(IC3-SW)')
    Net__IC6_DISCH_ = Net('Net-(IC6-DISCH)')
    Net__IC6_VBUS_EN_SNK_ = Net('Net-(IC6-VBUS_EN_SNK)')
    Net__IC6_VBUS_VS_DISCH_ = Net('Net-(IC6-VBUS_VS_DISCH)')
    Net__IC6_VREG_1V2_ = Net('Net-(IC6-VREG_1V2)')
    Net__IC6_VREG_2V7_ = Net('Net-(IC6-VREG_2V7)')
    Net__IC7_GATE_ = Net('Net-(IC7-GATE)')
    Net__IC8_TG_ = Net('Net-(IC8-TG)')
    Net__IC9_IN__ = Net('Net-(IC9-IN+)')
    Net__LS1___ = Net('Net-(LS1--)')
    Net__Q1_G_ = Net('Net-(Q1-G)')
    Net__Q3_G_ = Net('Net-(Q3-G)')
    Net__R21_Pad1_ = Net('Net-(R21-Pad1)')
    Net__R43_Pad2_ = Net('Net-(R43-Pad2)')
    Net__R46_Pad2_ = Net('Net-(R46-Pad2)')
    Net__R47_Pad2_ = Net('Net-(R47-Pad2)')
    Net__R48_Pad2_ = Net('Net-(R48-Pad2)')
    VDD = Net('VDD')

    # Components
    C1 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C1', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C10 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C10', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C11 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C11', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C12 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C12', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C13 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C13', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C14 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C14', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C15 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C15', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C16 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C16', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C17 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C17', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C18 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C18', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C19 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C19', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C2 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C2', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C20 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C20', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C21 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C21', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C22 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C22', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C23 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C23', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C24 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C24', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C25 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C25', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C26 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C26', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C27 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C27', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C28 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C28', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C29 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C29', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C3 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C3', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C30 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C30', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C31 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C31', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C32 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C32', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C33 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C33', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C34 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C34', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C35 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C35', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C37 = Part('EEV227M035A9MAA', 'EEV227M035A9MAA', value='220u', footprint='CAPAE830X1050N', ref='C37', fields={'Height': '10.5', 'Mouser Part Number': '80-EEV227M035A9MAA', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/KEMET/EEV227M035A9MAA?qs=T9vdlufmP8ywqIZcgRBkMQ%3D%3D', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'EEV227M035A9MAA', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    C4 = Part('Device', 'C_Small', value='1n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C4', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C102K3GAC', 'Mouser Part Number': '80-C0603C102K3G', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C5 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C5', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C6 = Part('Device', 'C_Small', value='1n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C6', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C102K3GAC', 'Mouser Part Number': '80-C0603C102K3G', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C7 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C7', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C8 = Part('Device', 'C_Small', value='10u', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C8', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'GRM188R6YA106MA73J', 'Mouser Part Number': '81-GRM188R6YA106MA3J', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    C9 = Part('Device', 'C_Small', value='100n', footprint='Capacitor_SMD:C_0603_1608Metric', ref='C9', fields={'Assembly Comment': '', 'Manufacturer_Name': 'KEMET', 'Manufacturer_Part_Number': 'C0603C104J5RACTU', 'Mouser Part Number': '80-C0603C104J5R', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'capacitor cap', 'ki_fp_filters': 'C_*'})
    D1 = Part('BAV199WQ-7', 'BAV199WQ-7', value='BAV199WQ-7', footprint='footprints:SOT65P210X110-3N', ref='D1', fields={'Height': '1.1', 'Mouser Part Number': '621-BAV199WQ-7', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/BAV199WQ-7?qs=xLhQT1EE4V%252BrO8tFabP6bQ%3D%3D', 'Manufacturer_Name': 'Diodes Incorporated', 'Manufacturer_Part_Number': 'BAV199WQ-7', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    D10 = Part('PMEG6020ER_115', 'PMEG6020ER,115', value='PMEG6020ER', footprint='footprints:PMEG6020ER115', ref='D10', fields={'Height': '1.1', 'Mouser Part Number': '771-PMEG6020ER-115', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Nexperia/PMEG6020ER115?qs=5DYmZrWuUErk3dU9e9SSpA%3D%3D', 'Manufacturer_Name': 'Nexperia', 'Manufacturer_Part_Number': 'PMEG6020ER,115', 'Assembly Comment': '', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    D2 = Part('BAV199WQ-7', 'BAV199WQ-7', value='BAV199WQ-7', footprint='footprints:SOT65P210X110-3N', ref='D2', fields={'Height': '1.1', 'Mouser Part Number': '621-BAV199WQ-7', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/BAV199WQ-7?qs=xLhQT1EE4V%252BrO8tFabP6bQ%3D%3D', 'Manufacturer_Name': 'Diodes Incorporated', 'Manufacturer_Part_Number': 'BAV199WQ-7', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    D3 = Part('SMF4L24AT1G', 'SMF4L24AT1G', value='SMF4L24AT1G', footprint='footprints:SODFL3619X98N', ref='D3', fields={'Height': '0.98', 'Mouser Part Number': '576-SMF4L24AT1G', 'Mouser Price/Stock': '', 'Manufacturer_Name': 'LITTELFUSE', 'Manufacturer_Part_Number': 'SMF4L24AT1G', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    D4 = Part('SMF4L24AT1G', 'SMF4L24AT1G', value='SMF4L24AT1G', footprint='footprints:SODFL3619X98N', ref='D4', fields={'Height': '0.98', 'Mouser Part Number': '576-SMF4L24AT1G', 'Mouser Price/Stock': '', 'Manufacturer_Name': 'LITTELFUSE', 'Manufacturer_Part_Number': 'SMF4L24AT1G', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    D5 = Part('Device', 'D_Schottky_Dual_Series_AKC', value='BAT54S', footprint='footprints:SOT95P230X110-3N', ref='D5', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Nexperia', 'Manufacturer_Part_Number': 'BAT54S,215', 'Mouser Part Number': '771-BAT54S-T/R', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Nexperia/BAT54S215?qs=me8TqzrmIYVOaf3j7zH0Wg%3D%3D', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'diode'})
    D6 = Part('Device', 'D_Schottky_Dual_Series_AKC', value='BAT54S', footprint='footprints:SOT95P230X110-3N', ref='D6', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Nexperia', 'Manufacturer_Part_Number': 'BAT54S,215', 'Mouser Part Number': '771-BAT54S-T/R', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Nexperia/BAT54S215?qs=me8TqzrmIYVOaf3j7zH0Wg%3D%3D', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'diode'})
    D7 = Part('Device', 'D_Schottky_Dual_Series_AKC', value='BAT54S', footprint='footprints:SOT95P230X110-3N', ref='D7', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Nexperia', 'Manufacturer_Part_Number': 'BAT54S,215', 'Mouser Part Number': '771-BAT54S-T/R', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Nexperia/BAT54S215?qs=me8TqzrmIYVOaf3j7zH0Wg%3D%3D', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'diode'})
    D8 = Part('Device', 'D_Schottky_Dual_Series_AKC', value='BAT54S', footprint='footprints:SOT95P230X110-3N', ref='D8', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Nexperia', 'Manufacturer_Part_Number': 'BAT54S,215', 'Mouser Part Number': '771-BAT54S-T/R', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Nexperia/BAT54S215?qs=me8TqzrmIYVOaf3j7zH0Wg%3D%3D', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'diode'})
    D9 = Part('PMEG6020ER_115', 'PMEG6020ER,115', value='PMEG6020ER', footprint='footprints:PMEG6020ER115', ref='D9', fields={'Height': '1.1', 'Mouser Part Number': '771-PMEG6020ER-115', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Nexperia/PMEG6020ER115?qs=5DYmZrWuUErk3dU9e9SSpA%3D%3D', 'Manufacturer_Name': 'Nexperia', 'Manufacturer_Part_Number': 'PMEG6020ER,115', 'Assembly Comment': '', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    F1 = Part('', '0154007.DRL_1', value='0154007.DR', footprint='footprints:0154100DR', ref='F1', fields={'Height': '3.81', 'Mouser Part Number': '576-0154007.DR', 'Manufacturer_Name': 'LITTELFUSE', 'Manufacturer_Part_Number': '0154007.DR', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    F2 = Part('SF-2410FP100W-2', 'SF-2410FP100W-2', value='SF-2410FP100W-2', footprint='footprints:SF2410FP100W2', ref='F2', fields={'Height': '2.36', 'Mouser Part Number': '652-SF-2410FP100W-2', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Bourns/SF-2410FP100W-2?qs=55YtniHzbhBKO2quK4sgow%3D%3D', 'Manufacturer_Name': 'Bourns', 'Manufacturer_Part_Number': 'SF-2410FP100W-2', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    FB1 = Part('BLM18HE601SN1D', 'BLM18HE601SN1D', value='BLM18HE601SN1D', footprint='Resistor_SMD:R_0603_1608Metric', ref='FB1', fields={'Height': '0.95', 'Mouser Part Number': '81-BLM18HE601SN1D', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Murata-Electronics/BLM18HE601SN1D?qs=%2F%252BYoplLUB5hymM76VL7Sqw%3D%3D', 'Manufacturer_Name': 'Murata Electronics', 'Manufacturer_Part_Number': 'BLM18HE601SN1D', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    FID1 = Part('Mechanical', 'Fiducial', value='Fiducial', footprint='Fiducial:Fiducial_0.75mm_Mask1.5mm', ref='FID1', fields={'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'fiducial marker', 'ki_fp_filters': 'Fiducial*'})
    FID2 = Part('Mechanical', 'Fiducial', value='Fiducial', footprint='Fiducial:Fiducial_0.75mm_Mask1.5mm', ref='FID2', fields={'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'fiducial marker', 'ki_fp_filters': 'Fiducial*'})
    FID3 = Part('Mechanical', 'Fiducial', value='Fiducial', footprint='Fiducial:Fiducial_0.75mm_Mask1.5mm', ref='FID3', fields={'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'fiducial marker', 'ki_fp_filters': 'Fiducial*'})
    H1 = Part('Mechanical', 'MountingHole', value='MountingHole', footprint='MountingHole:MountingHole_2.5mm', ref='H1', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'mounting hole', 'ki_fp_filters': 'MountingHole*'})
    H2 = Part('Mechanical', 'MountingHole', value='MountingHole', footprint='MountingHole:MountingHole_2.5mm', ref='H2', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'mounting hole', 'ki_fp_filters': 'MountingHole*'})
    IC1 = Part('TLV76733DRVR', 'TLV76733DRVR', value='TLV76733DRVR', footprint='footprints:SON65P200X200X80-7N', ref='IC1', fields={'Height': '0.8', 'Mouser Part Number': '595-TLV76733DRVR', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TLV76733DRVR?qs=9r4v7xj2LnmGIkwTuPlHig%3D%3D', 'Manufacturer_Name': 'Texas Instruments', 'Manufacturer_Part_Number': 'TLV76733DRVR', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    IC2 = Part('', 'OPA2387DSGT_1', value='OPA2387DSGT', footprint='footprints:SON50P200X200X80-9N', ref='IC2', fields={'Height': '0.8', 'Mouser Part Number': '595-OPA2387DSGT', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA2387DSGT?qs=MyNHzdoqoQIl7LJ1IzdkFA%3D%3D', 'Manufacturer_Name': 'Texas Instruments', 'Manufacturer_Part_Number': 'OPA2387DSGT', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    IC3 = Part('', 'LMR54406DBVR_1', value='LMR54406DBVR', footprint='SOT95P280X145-6N', ref='IC3', fields={'Height': '1.45', 'Mouser Part Number': '595-LMR54406DBVR', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LMR54406DBVR?qs=rSMjJ%252B1ewcQLNU8KVBwgHQ%3D%3D', 'Manufacturer_Name': 'Texas Instruments', 'Manufacturer_Part_Number': 'LMR54406DBVR', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    IC4 = Part('STM32G431CBT6', 'STM32G431CBT6', value='STM32G431CBT6', footprint='footprints:QFP50P900X900X160-48N', ref='IC4', fields={'Height': '1.6', 'Mouser Part Number': '511-STM32G431CBT6', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STM32G431CBT6?qs=T3oQrply3y8OocyGDXq5wg%3D%3D', 'Manufacturer_Name': 'STMicroelectronics', 'Manufacturer_Part_Number': 'STM32G431CBT6', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    IC5 = Part('TPD4E1U06DBVR', 'TPD4E1U06DBVR', value='TPD4E1U06DBVR', footprint='SOT95P280X145-6N', ref='IC5', fields={'Height': '1.45', 'Mouser Part Number': '595-TPD4E1U06DBVR', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPD4E1U06DBVR?qs=%2FCrDlo5IrVMRcCeY4Dk4aQ%3D%3D', 'Manufacturer_Name': 'Texas Instruments', 'Manufacturer_Part_Number': 'TPD4E1U06DBVR', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    IC6 = Part('STUSB4500QTR', 'STUSB4500QTR', value='STUSB4500QTR', footprint='footprints:QFN50P400X400X100-25N-D', ref='IC6', fields={'Height': '1', 'Mouser Part Number': '511-STUSB4500QTR', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STUSB4500QTR?qs=wUXugUrL1qyQbYMSzG1ujg%3D%3D', 'Manufacturer_Name': 'STMicroelectronics', 'Manufacturer_Part_Number': 'STUSB4500QTR', 'Assembly Comment': '', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    IC7 = Part('MAX16171ATA_VY+T', 'MAX16171ATA_VY+T', value='MAX16171ATA_VY+T', footprint='footprints:SON50P300X200X80-9N', ref='IC7', fields={'Height': '0.8', 'Mouser Part Number': '700-MAX16171ATA/VY+T', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Maxim-Integrated/MAX16171ATA-VY%2bT?qs=zW32dvEIR3uJUsRKfY9NHQ%3D%3D', 'Manufacturer_Name': 'Analog Devices', 'Manufacturer_Part_Number': 'MAX16171ATA/VY+T', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    IC8 = Part('LTC4440AHMS8E-5#PBF', 'LTC4440AHMS8E-5#PBF', value='LTC4440AHMS8E', footprint='footprints:SOP65P490X110-9N', ref='IC8', fields={'Height': '1.1', 'Mouser Part Number': '584-C4440AHMS8E-5PBF', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Analog-Devices/LTC4440AHMS8E-5PBF?qs=hVkxg5c3xu86VC%252BBJjm7uA%3D%3D', 'Manufacturer_Name': 'Analog Devices', 'Manufacturer_Part_Number': 'LTC4440AHMS8E-5#PBF', 'Assembly Comment': '', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    IC9 = Part('INA281A5QDBVRQ1', 'INA281A5QDBVRQ1', value='INA281A5QDBVRQ1', footprint='footprints:SOT95P280X145-5N', ref='IC9', fields={'Height': '1.45', 'Mouser Part Number': '595-INA281A5QDBVRQ1', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Texas-Instruments/INA281A5QDBVRQ1?qs=hd1VzrDQEGgwv71iGabWgQ%3D%3D', 'Manufacturer_Name': 'Texas Instruments', 'Manufacturer_Part_Number': 'INA281A5QDBVRQ1', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    J1 = Part('USB4110-GF-A', 'USB4110-GF-A', value='USB4110-GF-A', footprint='USB4110GFA', ref='J1', fields={'Height': '3.26', 'Mouser Part Number': '640-USB4110-GF-A', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/GCT/USB4110-GF-A?qs=KUoIvG%2F9IlYiZvIXQjyJeA%3D%3D', 'Manufacturer_Name': 'GCT (GLOBAL CONNECTOR TECHNOLOGY)', 'Manufacturer_Part_Number': 'USB4110-GF-A', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    J2 = Part('691243110009', '691243110009', value='691243110009', footprint='footprints:691243110009', ref='J2', fields={'Height': '9.2', 'Mouser Part Number': '710-691243110009', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Wurth-Elektronik/691243110009', 'Manufacturer_Name': 'Wurth Elektronik', 'Manufacturer_Part_Number': '691243110009', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    J3 = Part('', 'TSW-102-07-T-S_1', value='TSW-102-07-T-S', footprint='Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical', ref='J3', fields={'Height': '', 'Mouser Part Number': '200-TSW10207TS', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Samtec/TSW-102-07-T-S?qs=hzq9O0YpnZuE%252BS9CaLPVlQ%3D%3D', 'Manufacturer_Name': 'SAMTEC', 'Manufacturer_Part_Number': 'TSW-102-07-T-S', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes'})
    J4 = Part('61300611821', '61300611821', value='61300611821', footprint='footprints:RHDR6W97P0X254_1X6_1574X250X865P', ref='J4', fields={'Height': '8.65', 'Mouser Part Number': '710-61300611821', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Wurth-Elektronik/61300611821?qs=iLbezkQI%252BsgS21jF2eozhA%3D%3D', 'Manufacturer_Name': 'Wurth Elektronik', 'Manufacturer_Part_Number': '61300611821', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    J5 = Part('', 'TSW-102-07-T-S_1', value='TSW-102-07-T-S', footprint='footprints:TSW-102-XX-YY-S', ref='J5', fields={'Height': '', 'Mouser Part Number': '200-TSW10207TS', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Samtec/TSW-102-07-T-S?qs=hzq9O0YpnZuE%252BS9CaLPVlQ%3D%3D', 'Manufacturer_Name': 'SAMTEC', 'Manufacturer_Part_Number': 'TSW-102-07-T-S', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    J6 = Part('', 'TSW-102-07-T-S_1', value='TSW-102-07-T-S', footprint='footprints:TSW-102-XX-YY-S', ref='J6', fields={'Height': '', 'Mouser Part Number': '200-TSW10207TS', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Samtec/TSW-102-07-T-S?qs=hzq9O0YpnZuE%252BS9CaLPVlQ%3D%3D', 'Manufacturer_Name': 'SAMTEC', 'Manufacturer_Part_Number': 'TSW-102-07-T-S', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    J7 = Part('TSW-108-07-T-S', 'TSW-108-07-T-S', value='TSW-108-07-T-S', footprint='TSW-108-XX-YY-S', ref='J7', fields={'Height': '', 'Mouser Part Number': '200-TSW10807TS', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Samtec/TSW-108-07-T-S?qs=hzq9O0YpnZvsSJKdpkY6dA%3D%3D', 'Manufacturer_Name': 'SAMTEC', 'Manufacturer_Part_Number': 'TSW-108-07-T-S', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    J8 = Part('Connector', 'Conn_01x01_Pin', value='Conn_01x01_Pin', footprint='Connector_PinHeader_2.54mm:PinHeader_1x01_P2.54mm_Vertical', ref='J8', fields={'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'connector', 'ki_fp_filters': 'Connector*:*_1x??_*'})
    L1 = Part('SRP7028CC-150M', 'SRP7028CC-150M', value='SRP7028CC-150M', footprint='footprints:INDPM7366X300N', ref='L1', fields={'Height': '3', 'Mouser Part Number': '652-SRP7028CC-150M', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Bourns/SRP7028CC-150M?qs=1Kr7Jg1SGW%252BdV87frXW7uQ%3D%3D', 'Manufacturer_Name': 'Bourns', 'Manufacturer_Part_Number': 'SRP7028CC-150M', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    LS1 = Part('', 'CMI-9653S-SMT-TR_1', value='CMI-9653S-SMT-TR', footprint='footprints:CMI9653SSMTTR', ref='LS1', fields={'Height': '5', 'Mouser Part Number': '490-CMI-9653S-SMT-TR', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/CUI-Devices/CMI-9653S-SMT-TR?qs=qCxwlXJ4fnz7UpLQu8UKbg%3D%3D', 'Manufacturer_Name': 'CUI Devices', 'Manufacturer_Part_Number': 'CMI-9653S-SMT-TR', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    Q1 = Part('STL9P3LLH6', 'STL9P3LLH6', value='STL9P3LLH6', footprint='footprints:STL9P3LLH6', ref='Q1', fields={'Height': '', 'Mouser Part Number': '511-STL9P3LLH6', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STL9P3LLH6?qs=mKNKSX85ZJeHtH1e81LEbQ%3D%3D', 'Manufacturer_Name': 'STMicroelectronics', 'Manufacturer_Part_Number': 'STL9P3LLH6', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    Q2 = Part('STL10N3LLH5', 'STL10N3LLH5', value='STL10N3LLH5', footprint='footprints:STL10N3LLH5', ref='Q2', fields={'Height': '1', 'Mouser Part Number': '511-STL10N3LLH5', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STL10N3LLH5?qs=0gj%2FgiofzsOGxczN3DPYlA%3D%3D', 'Manufacturer_Name': 'STMicroelectronics', 'Manufacturer_Part_Number': 'STL10N3LLH5', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    Q3 = Part('2N7002NXAKR', '2N7002NXAKR', value='2N7002NXAKR', footprint='footprints:SOT95P230X110-3N', ref='Q3', fields={'Height': '1.1', 'Manufacturer_Name': 'Nexperia', 'Manufacturer_Part_Number': '2N7002NXAKR', 'Mouser Part Number': '771-2N7002NXAKR', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Nexperia/2N7002NXAKR?qs=%252B6g0mu59x7JoAsZYPFXqhw%3D%3D', 'Arrow Part Number': '2N7002NXAKR', 'Arrow Price/Stock': 'https://www.arrow.com/en/products/2n7002nxakr/nexperia?region=nac', 'Mouser Testing Part Number': '', 'Mouser Testing Price/Stock': '', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    R1 = Part('Device', 'R_Small', value='1k5', footprint='Resistor_SMD:R_0603_1608Metric', ref='R1', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-H3ED1501V', 'Mouser Part Number': '667-ERJ-H3ED1501V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R10 = Part('Device', 'R_Small', value='220k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R10', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RED2203V', 'Mouser Part Number': '667-ERJ-3RED2203V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R11 = Part('Device', 'R_Small', value='22k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R11', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-UP3J223V', 'Mouser Part Number': '667-ERJ-UP3J223V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R12 = Part('Device', 'R_Small', value='22k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R12', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-UP3J223V', 'Mouser Part Number': '667-ERJ-UP3J223V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R13 = Part('Device', 'R_Small', value='100', footprint='Resistor_SMD:R_0603_1608Metric', ref='R13', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-P03F1000V', 'Mouser Part Number': '667-ERJ-P03F1000V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R14 = Part('Device', 'R_Small', value='1k5', footprint='Resistor_SMD:R_0603_1608Metric', ref='R14', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-H3ED1501V', 'Mouser Part Number': '667-ERJ-H3ED1501V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R15 = Part('Device', 'R_Small', value='22k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R15', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-UP3J223V', 'Mouser Part Number': '667-ERJ-UP3J223V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R16 = Part('Device', 'R_Small', value='100', footprint='Resistor_SMD:R_0603_1608Metric', ref='R16', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-P03F1000V', 'Mouser Part Number': '667-ERJ-P03F1000V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R17 = Part('Device', 'R_Small', value='1k5', footprint='Resistor_SMD:R_0603_1608Metric', ref='R17', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-H3ED1501V', 'Mouser Part Number': '667-ERJ-H3ED1501V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R18 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R18', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R19 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R19', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R2 = Part('Device', 'R_Small', value='360k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R2', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RED3603V', 'Mouser Part Number': '667-ERJ-3RED3603V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R20 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R20', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R21 = Part('Device', 'R_Small', value='22k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R21', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-UP3J223V', 'Mouser Part Number': '667-ERJ-UP3J223V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R22 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R22', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R23 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R23', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R24 = Part('Device', 'R_Small', value='22k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R24', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-UP3J223V', 'Mouser Part Number': '667-ERJ-UP3J223V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R25 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R25', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R26 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R26', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R27 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R27', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R28 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R28', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R29 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R29', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R3 = Part('Device', 'R_Small', value='220k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R3', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RED2203V', 'Mouser Part Number': '667-ERJ-3RED2203V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R30 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R30', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R31 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R31', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R32 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R32', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R33 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R33', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R34 = Part('Device', 'R_Small', value='100', footprint='Resistor_SMD:R_0603_1608Metric', ref='R34', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-P03F1000V', 'Mouser Part Number': '667-ERJ-P03F1000V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R35 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R35', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R36 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R36', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R37 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R37', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R38 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R38', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R4 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R4', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R42 = Part('WSLP25125L000FEA', 'WSLP25125L000FEA', value='5m', footprint='footprints:RESC6432X89N', ref='R42', fields={'Height': '0.889', 'Mouser Part Number': '71-WSLP25125L000FEA', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Vishay-Dale/WSLP25125L000FEA?qs=2spUtbtSOvg97Y46VeGhKA%3D%3D', 'Manufacturer_Name': 'Vishay', 'Manufacturer_Part_Number': 'WSLP25125L000FEA', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    R43 = Part('Device', 'R_Small', value='100', footprint='Resistor_SMD:R_0603_1608Metric', ref='R43', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-P03F1000V', 'Mouser Part Number': '667-ERJ-P03F1000V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R44 = Part('Device', 'R_Small', value='1M', footprint='Resistor_SMD:R_0805_2012Metric', ref='R44', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-6GEYJ105V', 'Mouser Part Number': '667-ERJ-6GEYJ105V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R45 = Part('Device', 'R_Small', value='100m', footprint='Resistor_SMD:R_0805_2012Metric', ref='R45', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-6DSFR10V', 'Mouser Part Number': '667-ERJ-6DSFR10V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R46 = Part('Device', 'R_Small', value='100', footprint='Resistor_SMD:R_0603_1608Metric', ref='R46', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-P03F1000V', 'Mouser Part Number': '667-ERJ-P03F1000V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R47 = Part('Device', 'R_Small', value='100', footprint='Resistor_SMD:R_0603_1608Metric', ref='R47', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-P03F1000V', 'Mouser Part Number': '667-ERJ-P03F1000V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R48 = Part('Device', 'R_Small', value='100', footprint='Resistor_SMD:R_0603_1608Metric', ref='R48', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-P03F1000V', 'Mouser Part Number': '667-ERJ-P03F1000V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R49 = Part('Device', 'R_Small', value='10', footprint='Resistor_SMD:R_0603_1608Metric', ref='R49', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RED10R0V', 'Mouser Part Number': '667-ERJ-3RED10R0V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R5 = Part('Device', 'R_Small', value='1k5', footprint='Resistor_SMD:R_0603_1608Metric', ref='R5', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-H3ED1501V', 'Mouser Part Number': '667-ERJ-H3ED1501V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R50 = Part('Device', 'R_Small', value='10', footprint='Resistor_SMD:R_0603_1608Metric', ref='R50', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RED10R0V', 'Mouser Part Number': '667-ERJ-3RED10R0V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R6 = Part('Device', 'R_Small', value='4k7', footprint='Resistor_SMD:R_0603_1608Metric', ref='R6', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RBD4701V', 'Mouser Part Number': '667-ERJ-3RBD4701V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R7 = Part('Device', 'R_Small', value='360k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R7', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RED3603V', 'Mouser Part Number': '667-ERJ-3RED3603V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R8 = Part('Device', 'R_Small', value='360k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R8', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RED3603V', 'Mouser Part Number': '667-ERJ-3RED3603V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    R9 = Part('Device', 'R_Small', value='360k', footprint='Resistor_SMD:R_0603_1608Metric', ref='R9', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Panasonic', 'Manufacturer_Part_Number': 'ERJ-3RED3603V', 'Mouser Part Number': '667-ERJ-3RED3603V', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'ki_keywords': 'R resistor', 'ki_fp_filters': 'R_*'})
    S2 = Part('ADTSM644KVTR', 'ADTSM644KVTR', value='ADTSM644RVTR', footprint='footprints:ADTSM644RVTR', ref='S2', fields={'Height': '7.3', 'Mouser Part Number': '642-ADTSM644RVTR', 'Manufacturer_Name': 'Apem', 'Manufacturer_Part_Number': 'ADTSM644RVTR', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    S3 = Part('ADTSM644KVTR', 'ADTSM644KVTR', value='ADTSM644RVTR', footprint='footprints:ADTSM644RVTR', ref='S3', fields={'Height': '7.3', 'Mouser Part Number': '642-ADTSM644RVTR', 'Manufacturer_Name': 'Apem', 'Manufacturer_Part_Number': 'ADTSM644RVTR', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    TFT1 = Part('Adafruit_240x320_TFT', 'Adafruit_240x320_TFT', value='Adafruit_240x320_TFT', footprint='footprints:Adafruit_240x320_TFT', ref='TFT1', fields={'Manufacturer_Name': 'Adafruit', 'Manufacturer_Part_Number': '4311', 'Mouser Part Number': '485-4311', 'Mouser Price/Stock': 'https://www.mouser.co.uk/ProductDetail/Adafruit/4311?qs=P1JMDcb91o4a8KwJfafmzw%3D%3D', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    TP1 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP1', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP10 = Part('Connector', 'TestPoint', value='Current_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP10', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP11 = Part('Connector', 'TestPoint', value='TC_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP11', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP12 = Part('Connector', 'TestPoint', value='GND_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP12', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP13 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='footprints:TSW-101-XX-YY-S', ref='TP13', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP14 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP14', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP15 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP15', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP16 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP16', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP17 = Part('Connector', 'TestPoint', value='SW_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP17', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP2 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP2', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP3 = Part('Connector', 'TestPoint', value='3.3V_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP3', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP4 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP4', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP5 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP5', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP6 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP6', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP7 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP7', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP8 = Part('Connector', 'TestPoint', value='DIAG_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP8', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    TP9 = Part('Connector', 'TestPoint', value='Current_TP', footprint='TestPoint:TestPoint_Pad_D1.0mm', ref='TP9', fields={'Assembly Comment': 'N/A', 'Manufacturing comment': 'Do Not Place', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch', 'exclude_from_bom': 'yes', 'ki_keywords': 'test point tp', 'ki_fp_filters': 'Pin* Test*'})
    U2 = Part('PEC11J-9215F-S0015', 'PEC11J-9220F-S0015', value='PEC11J-9215F-S0015', footprint='footprints:PEC11J9215FS0015', ref='U2', fields={'Height': '25', 'Mouser Part Number': '652-PEC11J9215FS0015', 'Manufacturer_Name': 'Bourns', 'Manufacturer_Part_Number': 'PEC11J-9215F-S0015', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})
    U3 = Part('BSC014N04LS', 'BSC014N04LS', value='BSC014N04LS', footprint='footprints:BSC014N04LS', ref='U3', fields={'Assembly Comment': '', 'Manufacturer_Name': 'Infineon Technologies', 'Manufacturer_Part_Number': 'BSC014N04LSATMA1', 'Mouser Part Number': '726-BSC014N04LSATMA1', 'Manufacturing comment': '', 'Sheetname': 'Root', 'Sheetfile': 'AxxSolder.kicad_sch'})


    # Connections
    _p_3_3V += C15['1'], C16['1'], C17['1'], C2['1'], C20['2'], D1['2'], D2['2'], D5['2'], D6['2'], D7['2'], D8['2'], FB1['2'], IC1['1'], IC1['2'], IC2['8'], IC4['1'], IC4['2'], IC4['24'], IC4['36'], IC4['48'], IC9['5'], J4['2'], J7['1'], R18['1'], R19['1'], R20['1'], R26['2'], R27['2'], R35['2'], R36['1'], S2['2'], S3['2'], TP3['1'], U2['D1']
    _p_7_5V += C1['1'], C32['1'], C33['1'], C7['2'], C8['2'], D9['2'], IC1['4'], IC1['6'], IC8['3'], L1['2'], LS1['2'], R23['1'], R7['2'], R8['2']
    BLUE += D10['2'], J2['6'], R4['1'], R42['1']
    BOOST += C30['2'], C31['2'], D9['1'], IC8['6']
    Buzzer += IC4['44'], R34['1']
    CC1 += IC5['1'], IC6['1'], IC6['2'], J1['A5'], TP7['1']
    CC1_ += IC4['43'], TP1['1']
    CC2 += IC5['6'], IC6['4'], IC6['5'], J1['B5'], TP8['1']
    CC2_ += IC4['41'], TP2['1']
    CURRENT += C6['1'], IC4['6'], R49['1'], TP10['1']
    ENC_A += C29['1'], IC4['8'], R36['2'], R48['1']
    ENC_B += C28['1'], IC4['40'], R35['1'], R47['1']
    GREEN += F2['2'], J2['5'], R44['2'], R5['1']
    H_sense1 += C27['1'], J2['3'], R20['2'], R22['2']
    H_sense2 += C26['1'], J2['2'], R19['2'], R25['2']
    Handle_inp1 += D5['3'], IC4['12'], R22['1']
    Handle_inp2 += D6['3'], IC4['13'], R25['1']
    Heater += IC4['5'], IC8['1'], R38['1'], TP17['1']
    I_LEAK += IC4['9'], IC9['1'], TP9['1']
    NRST += C14['2'], IC4['7'], J4['3']
    RED += C30['1'], C31['1'], D10['1'], IC8['8'], J2['7'], R1['1'], U3['1']
    S1 += R16['2'], U2['E1']
    SCL += IC4['39'], IC6['7'], R26['1'], TP15['1']
    SDA += IC4['46'], IC6['8'], R27['1'], TP16['1']
    SD_CS += IC4['22'], J8['1']
    SPI_CS += IC4['28'], J7['6']
    SPI_DC += IC4['25'], J7['8']
    SPI_MOSI += IC4['29'], J7['5']
    SPI_RST += IC4['26'], J7['7']
    SPI_SCK += IC4['27'], J7['3']
    SW1 += C21['1'], IC4['42'], R16['1'], R30['1']
    SW2 += C22['1'], IC4['15'], R31['1'], R43['1']
    SW3 += C23['1'], IC4['45'], R32['1'], R46['1']
    SWCLK += IC4['38'], J1['B8'], J4['4']
    SWDIO += IC4['37'], J1['A8'], J4['5']
    S_sense += C25['1'], J2['1'], R18['2'], R29['2']
    Stand_inp += D8['3'], IC4['14'], R29['1']
    TC += C4['1'], IC4['11'], R50['1'], TP11['1']
    USART_RX += IC4['32'], TP13['1']
    USART_TX += IC4['31'], J4['6']
    USB_D_p += IC4['34'], IC5['4'], J1['A6'], J1['B6']
    USB_D_n += IC4['33'], IC5['3'], J1['A7'], J1['B7']
    USR1 += IC4['30'], TP4['1']
    USR2 += IC4['16'], TP6['1']
    USR3 += IC4['17'], TP5['1']
    USR4 += IC4['18'], J3['2'], TP14['1']
    VBUS += C10['2'], C11['1'], D3['1'], IC6['24'], J1['A4'], J1['A9'], J1['B4'], J1['B9'], Q1['1'], R12['2'], R14['2']
    VBUS_IN += D7['3'], IC4['10'], R28['2']
    VCCA += C18['1'], C19['1'], FB1['1'], IC4['20'], IC4['21']
    VDD_IN += F1['2'], IC7['8'], J2['9'], Q2['5']
    VDD_IN_USBCPD += C9['2'], IC7['2'], IC7['3'], IC7['4'], Q1['5'], Q2['1'], R17['2']
    Earth += IC9['4'], J2['4'], R45['1']
    GND += C1['2'], C10['1'], C11['2'], C12['2'], C13['2'], C14['1'], C15['2'], C16['2'], C17['2'], C18['2'], C19['2'], C2['2'], C20['1'], C21['2'], C22['2'], C23['2'], C24['2'], C25['2'], C26['2'], C27['2'], C28['2'], C29['2'], C32['2'], C33['2'], C34['1'], C35['1'], C37['2'], C4['2'], C5['1'], C6['2'], C7['1'], C8['1'], D1['1'], D2['1'], D3['2'], D4['2'], D5['1'], D6['1'], D7['1'], D8['1'], IC1['3'], IC1['5'], IC1['7'], IC2['4'], IC2['9'], IC3['2'], IC4['19'], IC4['23'], IC4['3'], IC4['35'], IC4['4'], IC4['47'], IC5['2'], IC6['10'], IC6['12'], IC6['13'], IC6['22'], IC6['25'], IC6['6'], IC7['5'], IC7['9'], IC8['2'], IC8['4'], IC8['9'], IC9['2'], J1['A1'], J1['A12'], J1['B1'], J1['B12'], J2['8'], J3['1'], J4['1'], J7['2'], Q3['2'], R11['1'], R2['2'], R3['2'], R30['2'], R31['2'], R32['2'], R33['2'], R37['2'], R38['2'], R42['2'], R6['2'], TP12['1'], U2['B1'], U2['MP']
    Net__C9_Pad1_ += C9['1'], R13['2']
    Net__C24_Pad1_ += C24['1'], R24['1'], R28['1'], R33['1']
    Net__IC2_Pad1_ += IC2['1'], R50['2'], R9['1']
    Net__IC2_Pad7_ += IC2['7'], R10['1'], R49['2']
    Net__IC2A_pos += D1['3'], IC2['3'], R1['2'], R2['1']
    Net__IC2A_neg += D2['3'], IC2['2'], R5['2'], R9['2']
    Net__IC2B_pos += IC2['5'], R3['1'], R4['2']
    Net__IC2B_neg += IC2['6'], R10['2'], R6['1']
    Net__IC3_CB_ += C3['1'], IC3['1']
    Net__IC3_FB_ += IC3['3'], R11['2'], R7['1'], R8['1']
    Net__IC3_SW_ += C3['2'], IC3['6'], L1['1']
    Net__IC6_DISCH_ += IC6['9'], R17['1']
    Net__IC6_VBUS_EN_SNK_ += IC6['16'], R15['1']
    Net__IC6_VBUS_VS_DISCH_ += IC6['18'], R14['1']
    Net__IC6_VREG_1V2_ += C13['1'], IC6['21']
    Net__IC6_VREG_2V7_ += C12['1'], IC6['23']
    Net__IC7_GATE_ += IC7['1'], Q2['4']
    Net__IC8_TG_ += IC8['7'], U3['9']
    Net__IC9_IN__ += F2['1'], IC9['3'], R44['1'], R45['2']
    Net__LS1___ += LS1['1'], Q3['3'], R23['2']
    Net__Q1_G_ += Q1['4'], R12['1'], R13['1'], R15['2']
    Net__Q3_G_ += Q3['1'], R34['2'], R37['1']
    Net__R21_Pad1_ += R21['1'], R24['2']
    Net__R43_Pad2_ += R43['2'], S2['1']
    Net__R46_Pad2_ += R46['2'], S3['1']
    Net__R47_Pad2_ += R47['2'], U2['A1']
    Net__R48_Pad2_ += R48['2'], U2['C1']
    VDD += C34['2'], C35['2'], C37['1'], C5['2'], D4['1'], F1['1'], IC3['4'], IC3['5'], R21['2'], U3['10']
    return


if __name__ == '__main__':
    import os

    # Detect desktop path across Windows, macOS, and Linux
    desktop = os.path.join(os.path.expanduser('~'), 'Desktop')
    os.makedirs(desktop, exist_ok=True)

    output_path = os.path.join(desktop, 'top.net')

    top()
    generate_netlist(file_=output_path)
    print(f"Netlist saved to: {output_path}")